<option value="ES">ESPA&Ntilde;A</option><br />
<option value="ESC">ESPA&Ntilde;A - CATALU&Ntilde;A</option><br />
<option value="ESB">ESPA&Ntilde;A - ISLAS BALEARES</option><br />
<option value="ESI">ESPA&Ntilde;A - ISLAS CANARIAS</option><br />
<option value="AF">AFGANISTAN</option><br />
<option value="AL">ALBANIA</option><br />
<option value="DE">ALEMANIA</option><br />
<option value="AD">ANDORRA</option><br />
<option value="AO">ANGOLA</option><br />
<option value="AI">ANGUILLA</option><br />
<option value="AG">ANTIGUA Y BARBUDA</option><br />
<option value="AN">ANTILLAS HOLANDESAS</option><br />
<option value="SA">ARABIA SAUDITA</option><br />
<option value="DZ">ARGELIA</option><br />
<option value="AR">ARGENTINA</option><br />
<option value="AM">ARMENIA</option><br />
<option value="AW">ARUBA</option><br />
<option value="AU">AUSTRALIA</option><br />
<option value="AT">AUSTRIA</option><br />
<option value="AZ">AZERBAIJAN</option><br />
<option value="BS">BAHAMAS</option><br />
<option value="BH">BAHREIN</option><br />
<option value="BD">BANGLADESH</option><br />
<option value="BB">BARBADOS</option><br />
<option value="BE">BELGICA</option><br />
<option value="BZ">BELICE</option><br />
<option value="BJ">BENIN</option><br />
<option value="BM">BERMUDA</option><br />
<option value="BT">BHUTAN</option><br />
<option value="BY">BIELORRUSIA</option><br />
<option value="BO">BOLIVIA</option><br />
<option value="BN">BORNEO</option><br />
<option value="BA">BOSNIA Y HERZEGOVINA</option><br />
<option value="BW">BOTSWANA</option><br />
<option value="BR">BRASIL</option><br />
<option value="BG">BULGARIA</option><br />
<option value="BF">BURKINA FASO</option><br />
<option value="BI">BURUNDI</option><br />
<option value="CV">CABO VERDE</option><br />
<option value="KH">CAMBOYA</option><br />
<option value="CM">CAMERUN</option><br />
<option value="CA">CANADA</option><br />
<option value="TD">CHAD</option><br />
<option value="CL">CHILE</option><br />
<option value="CN">CHINA</option><br />
<option value="CY">CHIPRE</option><br />
<option value="CO">COLOMBIA</option><br />
<option value="KM">COMORAS</option><br />
<option value="CG">CONGO</option><br />
<option value="CI">COSTA DE MARFIL</option><br />
<option value="CR">COSTA RICA</option><br />
<option value="HR">CROACIA</option><br />
<option value="CU">CUBA</option><br />
<option value="VA">VATICANO (SANTA SEDE)</option><br />
<option value="DK">DINAMARCA</option><br />
<option value="DJ">DJIBOUTI</option><br />
<option value="DM">DOMINICA</option><br />
<option value="EC">ECUADOR</option><br />
<option value="EG">EGIPTO</option><br />
<option value="SV">EL SALVADOR</option><br />
<option value="AE">EMIRATOS ARABES UNIDOS</option><br />
<option value="ER">ERITREA</option><br />
<option value="SK">ESLOVAQUIA</option><br />
<option value="SI">ESLOVENIA</option><br />
<option value="US">ESTADOS UNIDOS</option><br />
<option value="EE">ESTONIA</option><br />
<option value="ET">ETIOPIA</option><br />
<option value="RU">FEDERACION DE RUSIA</option><br />
<option value="FJ">FIJI</option><br />
<option value="PH">FILIPINAS</option><br />
<option value="FI">FINLANDIA</option><br />
<option value="FR">FRANCIA</option><br />
<option value="GA">GABON</option><br />
<option value="GM">GAMBIA</option><br />
<option value="GE">GEORGIA</option><br />
<option value="GH">GHANA</option><br />
<option value="GI">GIBRALTAR</option><br />
<option value="GD">GRANADA</option><br />
<option value="GR">GRECIA</option><br />
<option value="GL">GROENLANDIA</option><br />
<option value="GU">GUATEMALA</option><br />
<option value="GY">GUAYANA</option><br />
<option value="GN">GUINEA</option><br />
<option value="GQ">GUINEA ECUATORIAL</option><br />
<option value="GW">GUINEA-BISSAU</option><br />
<option value="HT">HAITI</option><br />
<option value="HN">HONDURAS</option><br />
<option value="HK">HONG KONG</option><br />
<option value="HU">HUNGRIA</option><br />
<option value="IN">INDIA</option><br />
<option value="ID">INDONESIA</option><br />
<option value="IR">IRAN</option><br />
<option value="IQ">IRAK</option><br />
<option value="IE">IRLANDA</option><br />
<option value="BV">ISLA BOUVET</option><br />
<option value="IS">ISLANDIA</option><br />
<option value="FK">ISLAS ( MALVINAS )</option><br />
<option value="KY">ISLAS CAIMAN</option><br />
<option value="CK">ISLAS COOK</option><br />
<option value="FO">ISLAS FEROE</option><br />
<option value="MP">ISLAS MARIANAS DEL NORTE</option><br />
<option value="SB">ISLAS SALOMON</option><br />
<option value="VG">ISLAS VIRGENES (REINO UNIDO )</option><br />
<option value="IL">ISRAEL</option><br />
<option value="IT">ITALIA</option><br />
<option value="JM">JAMAICA</option><br />
<option value="JP">JAPON</option><br />
<option value="JO">JORDANIA</option><br />
<option value="QA">KATAR</option><br />
<option value="KZ">KAZAJSTAN</option><br />
<option value="KE">KENIA</option><br />
<option value="KG">KIRGUISTAN</option><br />
<option value="KI">KIRIBATI</option><br />
<option value="KW">KUWAIT</option><br />
<option value="LB">LIBANO</option><br />
<option value="LS">LESOTO</option><br />
<option value="LV">LETONIA</option><br />
<option value="LR">LIBERIA</option><br />
<option value="LI">LIECHTENSEIN</option><br />
<option value="LT">LITUANIA</option><br />
<option value="LU">LUXEMBURGO</option><br />
<option value="MX">MEXICO</option><br />
<option value="MC">MONACO</option><br />
<option value="MO">MACAO</option><br />
<option value="MG">MADAGASCAR</option><br />
<option value="ML">MALI</option><br />
<option value="MY">MALASIA</option><br />
<option value="MW">MALAWI</option><br />
<option value="MV">MALDIVAS</option><br />
<option value="MT">MALTA</option><br />
<option value="MA">MARRUECOS</option><br />
<option value="MU">MAURICIO</option><br />
<option value="MR">MAURITANIA</option><br />
<option value="MN">MONGOLIA</option><br />
<option value="MS">MONTSERRAT</option><br />
<option value="MZ">MOZAMBIQUE</option><br />
<option value="MM">MYANMAR</option><br />
<option value="NE">NIGER</option><br />
<option value="NA">NAMIBIA</option><br />
<option value="NR">NARAU</option><br />
<option value="NP">NEPAL</option><br />
<option value="NI">NICARAGUA</option><br />
<option value="NG">NIGERIA</option><br />
<option value="NO">NORUEGA</option><br />
<option value="NZ">NUEVA ZELANDA</option><br />
<option value="OM">OMAN</option><br />
<option value="NL">PAISES BAJOS</option><br />
<option value="PK">PAKISTAN</option><br />
<option value="PW">PALAU</option><br />
<option value="PA">PANAMA</option><br />
<option value="PG">PAPUA NUEVA GUINEA</option><br />
<option value="PY">PARAGUAY</option><br />
<option value="PE">PERUACUTE</option><br />
<option value="PL">POLONIA</option><br />
<option value="PT">PORTUGAL</option><br />
<option value="GB">REINO UNIDO</option><br />
<option value="GB">REINO UNIDO - GRAN BRETA&Ntilde;A</option><br />
<option value="LY">REPUBLICA ARABE DE LIBIA</option><br />
<option value="CF">REPUBLICA CENTROAFRICANA</option><br />
<option value="CZ">REPUBLICA CHECA</option><br />
<option value="KR">REPUBLICA DE COREA</option><br />
<option value="MD">REPUBLICA DE MOLDOVA</option><br />
<option value="CD">REPUBLICA DEMOCRATICA DEL CONGO</option><br />
<option value="LA">REPUBLICA DEMOCRATICA POPULAR LAO</option><br />
<option value="DO">REPUBLICA DOMINICANA</option><br />
<option value="MK">REPUBLICA DE MACEDONIA DEL NORTE</option><br />
<option value="TZ">REPUBLICA UNIDA DE TANZANIA</option><br />
<option value="RW">RUANDA</option><br />
<option value="RO">RUMANIA</option><br />
<option value="EH">SAHARA OCCIDENTAL</option><br />
<option value="KN">SAINT KITTS Y NEVIS</option><br />
<option value="WS">SAMOA</option><br />
<option value="SM">SAN MARINO</option><br />
<option value="VC">SAN VICENTE Y LAS GRANADINAS</option><br />
<option value="LC">SANTA LUCIA</option><br />
<option value="ST">SAO TOME Y PRINCIPE</option><br />
<option value="SN">SENEGAL</option><br />
<option value="SL">SIERRA LEONA</option><br />
<option value="SG">SINGAPUR</option><br />
<option value="SY">SIRIA</option><br />
<option value="SO">SOMALIA</option><br />
<option value="LK">SRI LANKA</option><br />
<option value="SH">ST. HELENS</option><br />
<option value="ZA">SUDAFRICA</option><br />
<option value="SD">SUDAN</option><br />
<option value="SE">SUECIA</option><br />
<option value="CH">SUIZA</option><br />
<option value="SR">SURINAM ( GUAYANA HOLANDESA )</option><br />
<option value="SZ">SWAZILANDIA</option><br />
<option value="SC">SYCHELLES</option><br />
<option value="TN">TUNEZ</option><br />
<option value="TH">TAILANDIA</option><br />
<option value="TW">TAIWAN - PROVINCIA DE CHINA</option><br />
<option value="TJ">TAYIKISTAN</option><br />
<option value="TP">TIMOR DEL ESTE</option><br />
<option value="TG">TOGO</option><br />
<option value="TO">TONGA</option><br />
<option value="TT">TRINIDAD Y TOBAGO</option><br />
<option value="TC">TURCAS Y CAICOS</option><br />
<option value="TM">TURKMENISTAN</option><br />
<option value="TR">TURQUIA</option><br />
<option value="TV">TUVALU</option><br />
<option value="UA">UCRANIA</option><br />
<option value="UG">UGANDA</option><br />
<option value="UZ">URBEKISTAN</option><br />
<option value="UY">URUGUAY</option><br />
<option value="VU">VANUATU</option><br />
<option value="VE">VENEZUELA</option><br />
<option value="VN">VIET NAM</option><br />
<option value="YE">YEMEN</option><br />
<option value="YU">YUGOSLAVIA</option><br />
<option value="ZM">ZAMBIA</option><br />
<option value="ZW">ZIMBABUE</option>
